apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pyapp-deployment
  name: pyapp-deployment
  namespace: pyapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pyapp-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pyapp-deployment
    spec:
      containers:
        - image: ghcr.io/aminsaedi/pyapp:master
          name: pyapp
          ports:
            - containerPort: 8000
          resources: {}
status: {}
