apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pyapp-service
    name: amin
  name: pyapp-service
  namespace: pyapp
spec:
  ports:
    - name: main-port
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: pyapp-deployment
  type: ClusterIP
